// ERROR_ACTIONS
export const SET_ERROR = 'SET_ERROR';

//AUTH_ACTIONS
export const DEAUTHENTICATE = 'DEAUTHENTICATE';
export const AUTHENTICATE = 'AUTHENTICATE';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

//LOADER_ACTIONS
export const HANDLE_LOADER = 'HANDLE_LOADER';

//PARTICIPANTS_ACTIONS
export const SET_PARTICIPANT = 'SET_PARTICIPANT'
export const SET_PARTICIPANTS_COUNT = 'SET_PARTICIPANTS_COUNT'